spring:
  application:
    name: ApartmentPredictor

  datasource:
    url: jdbc:h2:file:/data/aptPredictor
    driverClassName: org.h2.Driver
    username: decin-co
    password: 1

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
